---
name: ci

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 1
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y daemonize
      - name: Run dex
        run: make start-dex-daemon
      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - name: Install dependencies
        run: go mod download
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          install-only: true
      - name: Check formatting
        run: make fmt
      - name: Run linters
        run: make lint
      - name: Run tests
        run: make test
